CREATE TABLE `_TABLE_CREATE_` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'уникальный код записи',
  `year` int(4) NOT NULL DEFAULT '0' COMMENT '(Year) год',
  `month` int(4) NOT NULL DEFAULT '0' COMMENT '(Mon) месяц',
  `account` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '(Счет) номер счёта',
  `kat_id` char(8) NOT NULL DEFAULT '-' COMMENT '! (KatID) категория счёта (RAD;TLF)',
  `fx` char(2) NOT NULL DEFAULT '*' COMMENT '! (fX) *-обычный; ap-абон_плата ФГУП',
  `date` date NOT NULL COMMENT '(Дата) дата выписки счёта',
  `rash_id` int(11) NOT NULL DEFAULT '0' COMMENT '! (RachID) код расчётчика, для ссылки на банк',
  `title_id` int(11) NOT NULL DEFAULT '0' COMMENT '! (IDЗаголовок) код заголовка счёта',
  `cid` int(11) NOT NULL DEFAULT '0' COMMENT '(IDЗаказчик) код клиента ',
  `uf` char(1) NOT NULL DEFAULT '-' COMMENT 'тип клиента: u-юрлица, f-физлица',
  `sf` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Счет-Фактура) номер счёт-фактуры',
  `datesf` date NOT NULL COMMENT '(ДатаСФ) дата выписки счёт-фактуры',
  `pt` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '(ПлатТребование) номер платёжного требования',
  `datept` date NOT NULL COMMENT '(ДатаПТ) дата выписки платёжного требования',
  `period1` date NOT NULL COMMENT '(Период1) за какой период выставлен счёт (дата1)',
  `period2` date NOT NULL COMMENT '(Период2) за какой период выставлен счёт (дата2)',
  `fperiod` tinyint(1) NOT NULL COMMENT '(fPeriod) выводить/не выводить заголовок документа "Услуги связи за период"',
  `sum` double(8,2) NOT NULL DEFAULT '0.00' COMMENT '(Сумма) сумма без НДС',
  `nds` double(8,2) NOT NULL DEFAULT '0.00' COMMENT '(НДС) ндс',
  `vsego` double(8,2) NOT NULL DEFAULT '0.00' COMMENT '(Всего)  всего с ндс',
  `dateopl` date NOT NULL COMMENT '(ДатаОплаты) последняя дата оплаты по счёту',
  `sumopl` double(8,2) NOT NULL DEFAULT '0.00' COMMENT '(Оплачено)',
  `dolg` double(8,2) NOT NULL DEFAULT '0.00' COMMENT '(Долг) долг за плательщиком',
  `sumbook` double(8,2) NOT NULL DEFAULT '0.00' COMMENT '(КнПрд) сумма для книги продаж',
  `prim` char(50) NOT NULL DEFAULT '' COMMENT '! (Примечание)',
  `fbreak` tinyint(1) NOT NULL COMMENT '(Анулирован) счёт аннулирован (да/нет)',
  `ts` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '(DTime) штам времени',
  PRIMARY KEY (`id`),
  UNIQUE KEY `year_month_account` (`year`,`month`,`account`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Книга продаж юрлиц для access-форм';