CREATE TABLE `_TABLE_CREATE_` (
  `id` int(4) NOT NULL AUTO_INCREMENT COMMENT 'id record',
  `nn` int(5) unsigned DEFAULT '0' COMMENT 'номер по порядку',
  `cust_a2` varchar(80) DEFAULT NULL COMMENT 'клиент из данных А2',
  `cust_rss` varchar(80) DEFAULT NULL COMMENT 'клиент из базы РСС',
  `cid` int(4) unsigned NOT NULL DEFAULT '0' COMMENT 'код клиента',
  `inn` varchar(80) DEFAULT NULL COMMENT 'ИНН',
  `serv_space` varchar(80) DEFAULT NULL COMMENT 'услуга и расположение',
  `bank_account` varchar(200) DEFAULT NULL COMMENT 'банк и счёт',
  `address_fact` varchar(500) DEFAULT NULL COMMENT ' адрес фактический',
  `address_u` varchar(80) DEFAULT NULL COMMENT 'адрес юридический',
  `phone` varchar(200) DEFAULT NULL COMMENT 'контактный номер(а)',
  `email` varchar(200) DEFAULT NULL COMMENT 'контактный адрес(а) почты',
  `inet_dog` varchar(80) DEFAULT NULL COMMENT 'интернет_договор и дата',
  `inet_speed` varchar(32) DEFAULT NULL COMMENT 'интернет_скорость',
  `inet_sum_nds` double(9,2) NOT NULL DEFAULT '0.00' COMMENT 'интернет_сум_с_ндс',
  `tel626_dog` varchar(80) DEFAULT NULL COMMENT 'тел626_договор и дата',
  `tel626_sum_nds` double(9,2) NOT NULL DEFAULT '0.00' COMMENT 'еуд626_сум_с_ндс',
  `tel642_dog` varchar(80) DEFAULT NULL COMMENT 'тел642_договор и дата',
  `tel642_sum_nds` double(9,2) NOT NULL DEFAULT '0.00' COMMENT 'тел642_сум_с_ндс',
  `mg_dog` varchar(80) DEFAULT NULL COMMENT 'МГ_договор и дата',
  `mg_sum_nds` double(9,2) NOT NULL DEFAULT '0.00' COMMENT 'МГ_сум_с_ндс',
  `to_dog` varchar(80) DEFAULT NULL COMMENT 'ТО_договор и дата',
  `to_sum_nds` double(9,2) NOT NULL DEFAULT '0.00' COMMENT 'ТО_сум_с_ндс',
  `pp_dog` varchar(80) DEFAULT NULL COMMENT 'ПП_договор и дата',
  `pp_sum_nds` double(9,2) NOT NULL DEFAULT '0.00' COMMENT 'ПП_сум_с_ндс',
  `all_sum_nds` double(9,2) NOT NULL DEFAULT '0.00' COMMENT 'общая_сумма_с_ндс',
  `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'штамп добавления/изменения записи',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='Клиенты А2 (a2_customers)';